### ISSUE TITLE
Killed

### ISSUE THREAD

**Issue by CGNAT** [jradrion/TEFLoN#2]
Hi,

I have attempted to run TEFLon both locally and on an HPC. However, in both settings, the job is killed before the teflon_prep has been completed. If I submit as a job, the memory 150GB is not enough to complete the job. Am I missing something?  

Thank you!

**Comment by jradrion** [comment]
Hi, 

Can you confirm that you are getting an OOM error when you are running teflon_prep_custom.py and not teflon_prep_annotation.py? The reason I ask is that teflon_prep_custom.py calls RepeatMasker, which, in my experience, can be very memory inefficient. Since you need to have RepeatMasker installed to run this script anyway, I would suggest trying to annotate your reference with the standalone RepeatMasker to see if you get the same OOM error. If it is indeed the case that 150gb of memory is not enough to run RepeatMasker on your reference genome, I might try an alternative TE annotation program to see if you have better results. You can use the annotation from any TE annotator with TEFLoN, provided you convert it to a BED file. Please let me know if this doesn't help.

Cheers,
Jeff
