### ISSUE TITLE
malformed mega_clustered.bed

### ISSUE THREAD

**Issue by pbasting** [jradrion/TEFLoN#8]
Hi @jradrion 

I've run into an issue with one of my samples while running TEFLoN. Here are the commands I used to prep annotations, map reads, and run TEFLoN
```bash
conda activate teflon
outdir=/scratch/pjb68507/test/teflon
cd $outdir
mkdir teflon_results
cores=32

python src/teflon/teflon_prep_annotation.py \
    -wd teflon_results/ \
    -a data/reference_te.bed \
    -t data/teflon_taxonomy.tsv \
    -f data/consensusTEs.fasta \
    -g data/dm6.fasta \
    -p teflon

bwa index teflon_results/teflon.prep_MP/teflon.mappingRef.fa

bwa mem \
    -t $cores \
    -Y teflon_results/teflon.prep_MP/teflon.mappingRef.fa \
    data/M_gor_S7_1.fq data/M_gor_S7_2.fq > mapped_reads.sam

samtools view -@ $cores -Sb mapped_reads.sam > mapped_reads.bam

samtools sort -@ $cores -o mapped_reads.sorted.bam mapped_reads.bam

samtools index mapped_reads.sorted.bam

echo -e "$outdir/mapped_reads.sorted.bam\tsample" > samples.tsv

python src/teflon/teflon.v0.4.py \
    -wd teflon_results/ \
    -d teflon_results/teflon.prep_TF/ \
    -s samples.tsv \
    -i sample \
    -l1 family \
    -l2 family \
    -t $cores \
    -q 20
```
* I ran everything within a conda environment that can be recreated with this yaml:
```yaml
name: teflon
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - samtools=1.3
  - bwa=0.7.17
  - repeatmasker=4.1.0
  - bedtools=2.17.0
  - gawk=5
```
##
* while executing the `teflon.v0.4.py` step, I get an error from samtools:
```
cmd: samtools view -@ 32 -q 20 -L /scratch/pjb68507/test/teflon/teflon_results/sample.bed_files/mega_clustered.bed /scratch/pjb68507/test/teflon/mapped_reads.sorted.bam -b
Error running samtools: p.returncode = 1
```
* This is caused by the `mega_clustered.bed` being malformed and unreadable by samtools.
```bash
$ awk -F"\t" 'NF!=3{print $0}' teflon_results/sample.bed_files/mega_clustered.bed
chrX    13128878        13117.6 287     2438
0645341
chr3L   6111493S18      1571    1718
42325   13542472
```
* Most of the `mega_clustered.bed` file is fine, but it looks like some of the lines are being merged together or truncated, resulting in entries with more/less than three columns.
* I've also received a similar error report on a [McClintock](https://github.com/bergmanlab/mcclintock) issue when @zhjpeng ran TEFLoN through McClintock here: https://github.com/bergmanlab/mcclintock/issues/76#issuecomment-761018575
* Others in my lab and I have run TEFLoN through McClintock many times without issue but it seems that this particular sample (and @zhjpeng 's sample) is triggering the error, and I'm able to replicate it on repeated runs.
* I am running this with unpublished reads, but I'd be happy to provide them, or any of the other input or log files, if necessary to work out this bug.

Thanks for the help,

Preston

**Comment by jradrion** [comment]
Hi @pbasting, sorry for the issues you've been having. It's not obvious to me what is going on with that bed file. Given that this issue appears to be sample specific, I doubt I'd be able to debug it without access to your input data. Please email me at jadrion@uoregon.edu to discuss the best way for us to proceed.

**Comment by jradrion** [comment]
Hi @pbasting, I just sent you an email about a potential resolution to this issue. I believe this error was caused by having consensus TE sequences in your reference (`data/dm6.fasta`). Consensus sequences are automatically appended to your reference before mapping when you use the `-f data/consensusTEs.fasta` option in `teflon_prep_annotation.py`, so you shouldn't need them in the reference prior to that. I realize that the directions I provided were not explicit about this and I will be editing them for clarity.

Sorry this took so long. Let me know if you feel like the issue is sufficiently resolved and I'll go ahead and close it.

Best,
Jeff

**Comment by pbasting** [comment]
Thanks for looking into this @jradrion . I'll try running the sample without adding the consensus sequences to the reference and let you know how it works.

**Comment by jradrion** [comment]
Thanks, @pbasting! However, there was a bug in the code that was causing `mega_clustered.bed` to be incorrectly formatted from time to time when multiple processes wrote to the same output file simultaneously (dumb idea). I no longer think that error was caused by having consensus TE sequences in the reference fasta file, although you still shouldn't have them in there. I just pushed a change that should fix the issue for you. Your files ran fine on my end. Please let me know if everything is working on your end, at your convenience of course.

**Comment by pbasting** [comment]
Ok great! That makes sense. I'll continue to not add consensus TE sequences to the reference fasta and run again with the TEFLoN code from: https://github.com/jradrion/TEFLoN/commit/3e2d67886b70644fd1f7d79263b3c8dbed639e46. I'll update you with the results when it completes.

Thanks!
Preston

**Comment by pbasting** [comment]
@jradrion The sample I was having issues with was able to complete with the new updated TEFLoN, though it did take a bit longer than I expected (~8 days with 28 cores). Not sure if this long run time is specific to this sample but I can test it out on other samples of comparable size to see. Otherwise, it is working as expected now. Thanks for resolving this issue!

-Preston
